### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by RiboPg** [D-K-E/ptm-viewer#3]
Hi, when i launch app.my this gave me arrayfire not found.
How can i solve this issue?
thank you

**Comment by D-K-E** [comment]
Hi thanks for the report.
The code would change a lot in the up coming days.
But if you really just one to explore the code. 
You can checkout the commit "17befa86f6db2bbf3" in branch dev.
If you have the necessary libraries you can then launch the from the
top folder by `python main/app.py`.

I suggest in any case to wait a little for me to finish the new opengl backend if you want to use the app for something.
