### ISSUE TITLE
PySide2.shiboken2

### ISSUE THREAD

**Issue by FrancescaPimpinelli** [D-K-E/ptm-viewer#6]
Hi Kaan!
I'm trying to run qtapp.py but, even if I have installed PySide2 and shiboken2 and every packages and dependencies are correctly installed, it is still giving me this error:
Traceback (most recent call last):
  File "qtapp.py", line 9, in <module>
    from PySide2.shiboken2 import VoidPtr
ModuleNotFoundError: No module named 'PySide2.shiboken2'

Do you have any idea?
Thank you!

**Comment by D-K-E** [comment]
Hi,
Did you try to install the libraries from spec file or did you install the latest ones ?

**Comment by FrancescaPimpinelli** [comment]
I have installed the libraries from spec file, but it gave me this error; so I installed PySide2 and shiboken2 on both python2 and python3. Still happens!

**Comment by D-K-E** [comment]
So far I can not reproduce the error. But I remember dealing with this error while I was trying out different versions of pyside2 and qt. Would you mind checking the version of your pyside2 installation. It should be `5.11.0` and another thing is you should not import the `VoidPtr` from `shiboken2` library directly installed from pypi. You need to use the one that is included in `PySide2`. I will be commiting an enviroment.yml file as well for installation. If the above solution does not work, try recreating the environment from the yml file

**Comment by FrancescaPimpinelli** [comment]
I managed to solve this problem, thank you!
But it gives me this error now:
Traceback (most recent call last):
  File "qtapp.py", line 17, in <module>
    from ptmviewer.glwidget import PtmLambertianGLWidget, PtmNormalMapGLWidget
  File "/home/pimpi/ptm-viewer/ptmviewer/glwidget.py", line 885, in <module>
    class PtmPerChannelNormalMapGLWidget(PtmNormalMapGLWidget):
  File "/home/pimpi/ptm-viewer/ptmviewer/glwidget.py", line 890, in PtmPerChannelNormalMapGLWidget
    parent=None):
NameError: name 'Tuple' is not defined

**Comment by D-K-E** [comment]
Probably `glwidget` lacks an import statement at the top. Something like `from typing import Tuple`.

I am preparing another large commit on master. It should be more or less ready by the end of this week. I will fix it as a part of it, but if you want to try some stuff, you can add the import statement, and see what it gives
