### ISSUE TITLE
Loading .ptm files

### ISSUE THREAD

**Issue by FrancescaPimpinelli** [D-K-E/ptm-viewer#7]
Hi Kaan!
Thanks to your dev committies I managed to open the program, so thank you very much.
Now, if I try to load a .ptm file it gives me this error:

Gtk-Message: 15:44:48.049: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "qtapp.py", line 114, in loadPtm
    ptmobj = self.ptmfiles[cindex]
KeyError: <PySide2.QtCore.QModelIndex(-1,-1,0x0,QObject(0x0))  at 0x7f78a5a57f08>

Do you know how I could solve this?
Thank you again!

**Comment by D-K-E** [comment]
That error is about not being able to find the loaded ptm file. Do you by any chance try to load the ptm file to scene without selecting it first ? And please do not use lambertian shader but PerChannelNormalMapDir, the others are not working so well for now

**Comment by FrancescaPimpinelli** [comment]
Hi! I followed your advice (selecting before loading and choosing PerChannelNormalMapDir shader), now it gives me that:

Gtk-Message: 14:29:26.740: GtkDialog mapped without a transient parent. This is discouraged.
gl initialized in app
QOpenGLShader::compile(Vertex): 0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

*** Problematic Vertex shader source code ***

#version 330 core
#define lowp
#define mediump
#define highp
#line 2
layout (location = 0) in vec3 aPos;

uniform mat4 projection;
uniform mat4 view;
uniform mat4 model;

void main()
{
    gl_Position = projection * view * model * vec4(aPos, 1.0);
}

***
0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Traceback (most recent call last):
  File "/home/pimpi/ptm-viewer/ptmviewer/ptm-viewer-dev/ptmviewer/ptmviewer/glwidget.py", line 479, in initializeGL
    self.lampShader_init(self.lampShaderName)
  File "/home/pimpi/ptm-viewer/ptmviewer/ptm-viewer-dev/ptmviewer/ptmviewer/glwidget.py", line 387, in lampShader_init
    vshader = self.loadVertexShader(shname, fromFile=False)
  File "/home/pimpi/ptm-viewer/ptmviewer/ptm-viewer-dev/ptmviewer/ptmviewer/glwidget.py", line 96, in loadVertexShader
    return self.loadShader(shaderName, "vertex", fromFile)
  File "/home/pimpi/ptm-viewer/ptmviewer/ptm-viewer-dev/ptmviewer/ptmviewer/glwidget.py", line 89, in loadShader
    shaderType, shaderName, shaderSource
ValueError: vertex shader 
#version 330 core
layout (location = 0) in vec3 aPos;

uniform mat4 projection;
uniform mat4 view;
uniform mat4 model;

void main()
{
    gl_Position = projection * view * model * vec4(aPos, 1.0);
}
 known as lamp is not compiled
/home/pimpi/ptm-viewer/ptmviewer/ptm-viewer-dev/ptmviewer/ptmviewer/glwidget.py:1019: RuntimeWarning: SbkConverter: Unimplemented C++ array type.
  self.program.setUniformValue("projection", projectionMatrix)
QOpenGLShaderProgram::uniformLocation(projection): shader program is not linked
Errore di segmentazione (core dump creato)

Any suggestion?

**Comment by D-K-E** [comment]
I see this is a different issue than loading. It is about the opengl support of your graphic card. I will close this issue now. Let's discuss this under #8
